# Generated by Django 2.0.6 on 2018-06-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('KMD', '한의사')], max_length=30),
        ),
    ]
