# Generated by Django 2.0.6 on 2018-06-25 03:02

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180625_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Survey Time of Patient')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified Datetime')),
                ('ref_file', models.FileField(upload_to=web.models.survey_file_directory_path)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Survey'),
        ),
    ]
