# Generated by Django 2.0.6 on 2018-06-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180625_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.Survey'),
        ),
    ]
