# Generated by Django 2.0.6 on 2018-06-25 06:05

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180625_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='ref_file',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_json',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
